# TCL File Generated by Component Editor 15.0
# Thu Dec 07 20:39:53 CST 2017
# DO NOT MODIFY


# 
# Audio_Slave "Audio_Slave" v1.0
#  2017.12.07.20:39:53
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module Audio_Slave
# 
set_module_property DESCRIPTION ""
set_module_property NAME Audio_Slave
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP TE401
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Audio_Slave
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL new_component
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_audio_interface.sv SYSTEM_VERILOG PATH avalon_audio_interface.sv TOP_LEVEL_FILE
add_fileset_file i2s_receive.v VERILOG PATH i2s_receive.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_audio_interface.sv SYSTEM_VERILOG PATH avalon_audio_interface.sv
add_fileset_file i2s_receive.v VERILOG PATH i2s_receive.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point CLK
# 
add_interface CLK clock end
set_interface_property CLK clockRate 50000000
set_interface_property CLK ENABLED true
set_interface_property CLK EXPORT_OF ""
set_interface_property CLK PORT_NAME_MAP ""
set_interface_property CLK CMSIS_SVD_VARIABLES ""
set_interface_property CLK SVD_ADDRESS_GROUP ""

add_interface_port CLK CLK clk Input 1


# 
# connection point RESET
# 
add_interface RESET reset end
set_interface_property RESET associatedClock CLK
set_interface_property RESET synchronousEdges DEASSERT
set_interface_property RESET ENABLED true
set_interface_property RESET EXPORT_OF ""
set_interface_property RESET PORT_NAME_MAP ""
set_interface_property RESET CMSIS_SVD_VARIABLES ""
set_interface_property RESET SVD_ADDRESS_GROUP ""

add_interface_port RESET RESET reset Input 1


# 
# connection point AUDIO_SLAVE
# 
add_interface AUDIO_SLAVE avalon end
set_interface_property AUDIO_SLAVE addressUnits WORDS
set_interface_property AUDIO_SLAVE associatedClock CLK
set_interface_property AUDIO_SLAVE associatedReset RESET
set_interface_property AUDIO_SLAVE bitsPerSymbol 8
set_interface_property AUDIO_SLAVE burstOnBurstBoundariesOnly false
set_interface_property AUDIO_SLAVE burstcountUnits WORDS
set_interface_property AUDIO_SLAVE explicitAddressSpan 0
set_interface_property AUDIO_SLAVE holdTime 0
set_interface_property AUDIO_SLAVE linewrapBursts false
set_interface_property AUDIO_SLAVE maximumPendingReadTransactions 0
set_interface_property AUDIO_SLAVE maximumPendingWriteTransactions 0
set_interface_property AUDIO_SLAVE readLatency 0
set_interface_property AUDIO_SLAVE readWaitStates 0
set_interface_property AUDIO_SLAVE readWaitTime 0
set_interface_property AUDIO_SLAVE setupTime 0
set_interface_property AUDIO_SLAVE timingUnits Cycles
set_interface_property AUDIO_SLAVE writeWaitTime 0
set_interface_property AUDIO_SLAVE ENABLED true
set_interface_property AUDIO_SLAVE EXPORT_OF ""
set_interface_property AUDIO_SLAVE PORT_NAME_MAP ""
set_interface_property AUDIO_SLAVE CMSIS_SVD_VARIABLES ""
set_interface_property AUDIO_SLAVE SVD_ADDRESS_GROUP ""

add_interface_port AUDIO_SLAVE AVL_ADDR address Input 4
add_interface_port AUDIO_SLAVE AVL_CS chipselect Input 1
add_interface_port AUDIO_SLAVE AVL_READ read Input 1
add_interface_port AUDIO_SLAVE AVL_WRITE write Input 1
add_interface_port AUDIO_SLAVE AVL_WRITEDATA writedata Input 32
add_interface_port AUDIO_SLAVE AVL_READDATA readdata Output 32
set_interface_assignment AUDIO_SLAVE embeddedsw.configuration.isFlash 0
set_interface_assignment AUDIO_SLAVE embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment AUDIO_SLAVE embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment AUDIO_SLAVE embeddedsw.configuration.isPrintableDevice 0


# 
# connection point GPIO_DIN
# 
add_interface GPIO_DIN conduit end
set_interface_property GPIO_DIN associatedClock CLK
set_interface_property GPIO_DIN associatedReset RESET
set_interface_property GPIO_DIN ENABLED true
set_interface_property GPIO_DIN EXPORT_OF ""
set_interface_property GPIO_DIN PORT_NAME_MAP ""
set_interface_property GPIO_DIN CMSIS_SVD_VARIABLES ""
set_interface_property GPIO_DIN SVD_ADDRESS_GROUP ""

add_interface_port GPIO_DIN GPIO_DIN GPIO_DIN Input 1


# 
# connection point GPIO_DIN2
# 
add_interface GPIO_DIN2 conduit end
set_interface_property GPIO_DIN2 associatedClock CLK
set_interface_property GPIO_DIN2 associatedReset RESET
set_interface_property GPIO_DIN2 ENABLED true
set_interface_property GPIO_DIN2 EXPORT_OF ""
set_interface_property GPIO_DIN2 PORT_NAME_MAP ""
set_interface_property GPIO_DIN2 CMSIS_SVD_VARIABLES ""
set_interface_property GPIO_DIN2 SVD_ADDRESS_GROUP ""

add_interface_port GPIO_DIN2 GPIO_DIN2 GPIO_DIN2 Input 1


# 
# connection point AUD_BCLK
# 
add_interface AUD_BCLK conduit end
set_interface_property AUD_BCLK associatedClock CLK
set_interface_property AUD_BCLK associatedReset RESET
set_interface_property AUD_BCLK ENABLED true
set_interface_property AUD_BCLK EXPORT_OF ""
set_interface_property AUD_BCLK PORT_NAME_MAP ""
set_interface_property AUD_BCLK CMSIS_SVD_VARIABLES ""
set_interface_property AUD_BCLK SVD_ADDRESS_GROUP ""

add_interface_port AUD_BCLK AUD_BCLK AUD_BCLK Input 1


# 
# connection point AUD_ADCLRCK
# 
add_interface AUD_ADCLRCK conduit end
set_interface_property AUD_ADCLRCK associatedClock CLK
set_interface_property AUD_ADCLRCK associatedReset RESET
set_interface_property AUD_ADCLRCK ENABLED true
set_interface_property AUD_ADCLRCK EXPORT_OF ""
set_interface_property AUD_ADCLRCK PORT_NAME_MAP ""
set_interface_property AUD_ADCLRCK CMSIS_SVD_VARIABLES ""
set_interface_property AUD_ADCLRCK SVD_ADDRESS_GROUP ""

add_interface_port AUD_ADCLRCK AUD_ADCLRCK AUD_ADCLRCK Input 1


# 
# connection point codec_left
# 
add_interface codec_left conduit end
set_interface_property codec_left associatedClock CLK
set_interface_property codec_left associatedReset RESET
set_interface_property codec_left ENABLED true
set_interface_property codec_left EXPORT_OF ""
set_interface_property codec_left PORT_NAME_MAP ""
set_interface_property codec_left CMSIS_SVD_VARIABLES ""
set_interface_property codec_left SVD_ADDRESS_GROUP ""

add_interface_port codec_left codec_left codec_left Output 32


# 
# connection point codec_right
# 
add_interface codec_right conduit end
set_interface_property codec_right associatedClock CLK
set_interface_property codec_right associatedReset RESET
set_interface_property codec_right ENABLED true
set_interface_property codec_right EXPORT_OF ""
set_interface_property codec_right PORT_NAME_MAP ""
set_interface_property codec_right CMSIS_SVD_VARIABLES ""
set_interface_property codec_right SVD_ADDRESS_GROUP ""

add_interface_port codec_right codec_right codec_right Output 32

